#QUIPUZCOA LOPEZ YULEISY
print("OPERACIONES BÁSICAS")
print("═══════════════════")
num1 = float(input("Ingrese un primer número: "))
num2 = float(input("Ingrese un segundo número: "))
num3 = float(input("Ingrese un tercer número: "))
print("¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯")
print( "Suma: ", num1+num2+num3)
print( "Resta: ", num1-num2-num3)
print( "Multiplicación: ", num1*num2*num3)
print ("División normal: ", num1/num2/num3)
print ("División entera: ", num1//num2//num3)
